version: '3'
services:

  teamcity:
    container_name: teamcity
    image: jetbrains/teamcity-server:latest
    restart: always
    hostname: ${TEAMCITY_HOSTNAME}
    ports:
      - '8111:8111'
    volumes:
      - './datadir:/data/teamcity_server/datadir'
      - './logs:/opt/teamcity/logs'